config/routes.rb
VboxwebRb::Application.routes.draw do |map|
  match 'vm/imports'              => 'import#index',    :as => 'vm_imports'
  match 'vm/imports/new'          => 'import#new',      :as => 'vm_new_import'
  match 'vm/imports/upload'       => 'import#upload',   :as => 'vm_upload_import'
  match 'vm/imports/:id/progress' => 'import#progress', :as => 'vm_import_progress'
  match 'vm/imports/:id/destroy'  => 'import#destroy',  :as => 'vm_import_destroy'
  match 'vm/imports/:id'          => 'import#show',     :as => 'vm_import'
  
  match 'vm/:uuid/exports'              => 'export#index',    :as => 'vm_exports'
  match 'vm/:uuid/exports/new'          => 'export#new',      :as => 'vm_new_export'
  match 'vm/:uuid/exports/:id/progress' => 'export#progress', :as => 'vm_export_progress'
  match 'vm/:uuid/exports/:id/download' => 'export#download', :as => 'vm_export_download'
  match 'vm/:uuid/exports/:id/destroy'  => 'export#destroy',  :as => 'vm_export_destroy'
  match 'vm/:uuid/exports/:id'          => 'export#show',     :as => 'vm_export'

  match 'vm/:uuid/snapshots'             => 'snapshots#index',   :as => 'vm_snapshots'
  match 'vm/:uuid/snapshots/new'         => 'snapshots#new',     :as => 'vm_new_snapshot'
  match 'vm/:uuid/snapshots/:id/restore' => 'snapshots#restore', :as => 'vm_snapshot_restore'
  match 'vm/:uuid/snapshots/:id/destroy' => 'snapshots#destroy', :as => 'vm_snapshot_destroy'
  match 'vm/:uuid/snapshots/:id'         => 'snapshots#show',    :as => 'vm_snapshot'

  match 'vm/:uuid/settings' => 'vm#settings', :as => 'vm_settings'
  match 'vm/:uuid/destroy'  => 'vm#destroy',  :as => 'vm_destroy'
  match 'vm/:uuid/:command' => 'vm#control',  :as => 'vm_control'
  match 'vm/:uuid'          => 'vm#show',     :as => 'vm'

  match 'hd/:uuid/release' => 'hd#release', :as => 'hd_release'
  match 'hd/:uuid/remove'  => 'hd#remove',  :as => 'hd_remove'
  match 'hd/:uuid'         => 'hd#show',    :as => 'hd'

  root :to => 'homepage#index'
end

app/models/import.rb
class Import < ActiveRecord::Base

  validates_presence_of :filepath

  before_create :set_status_and_percent_imported_if_blank

  STATUSES = {
    :starting => 'Starting...',
    :failed => 'Failed...',
    :importing => 'Importing...',
    :completed => "Completed"
  }

  Import::STATUSES.keys.each do |status_value|
    define_method "#{status_value}?" do
      status.to_s.downcase == status_value.to_s
    end
  end

  def upload(archive_file)
    filename = archive_file.original_filename.gsub(/[^\w\d\-\.]/i, '_').gsub(/(^_*|_*$)/i, '').split('.')[0..-2].join('.')

    if filename.blank?
      errors[:base] << "You must upload an OVF file with a valid filename containing only letters, numbers, underscores, dashes, and periods."
      FileUtils.rm_rf(archive_file.path) rescue nil
      return false
    end

    dest_path = Rails.root.join("imports/#{filename}")

    if File.directory?(dest_path.to_s)
     errors[:base] << "Looks like an import of this name already exists. Please rename the archive file and try again."
     FileUtils.rm_rf(archive_file.path) rescue nil
     return false
    end

    FileUtils.mkdir_p(dest_path.to_s)

    Dir.chdir(dest_path.to_s) do
      require 'zlib'
      require 'archive/tar/minitar'
      Archive::Tar::Minitar.unpack(archive_file.path, dest_path.to_s)
      ovf_file = Dir['*.ovf'].first

      if ovf_file.blank?
        errors[:base] << "No OVF file was found within the uploaded archive #{archive_file.original_filename}."
        FileUtils.rm_rf(dest_path.to_s) rescue nil
        FileUtils.rm_rf(archive_file.path) rescue nil
        return false
      end

      return false unless valid_ovf_file?(dest_path.join(ovf_file).to_s)
    end

    true # upload successful
  end

  def import!
    update_attribute(:status, 'importing')
    vm = VirtualBox::VM.import(filepath) do |progress|
      update_attribute(:percent_imported, progress.percent)
    end
    update_attribute(:machine_uuid, vm.uuid)
    update_attribute(:status, 'completed')
  rescue
    update_attribute(:status, 'failed')
  end
  handle_asynchronously :import!

  def machine
    return unless completed?
    @machine ||= VirtualBox::VM.find(machine_uuid)
  end

  private

  def set_status_and_percent_imported_if_blank
    self.status = 'starting' if self.status.blank?
    self.percent_imported = 0 if self.percent_imported.blank?
  end

  def valid_ovf_file?(filepath)
    begin
      # Check that the file is readable (makes sure that they supplied a correct OVF filepath)
      VirtualBox::Appliance.new(filepath)
      true
    rescue VirtualBox::Exceptions::FileErrorException, VirtualBox::Exceptions::FFIException
      errors[:base] << "The filepath or import archive supplied cannot be successfully read. Was it an OVF file?"
      false
    end
  end

  def validate
    if !filepath || !File.exist?(filepath)
      errors[:base] << "You must specify a valid filepath."
      false
    else
      valid_ovf_file?(filepath)
    end
  end

end

app/controllers/import_controller.rb
class ImportController < ApplicationController
  before_filter :find_import_from_id, :except => [:index, :new, :upload]

  def index
  end

  def show
  end

  def new
    if request.post?
      import = Import.new(:filepath => params[:import][:filepath])
      if import.save
        import.import!
        flash[:notice] = "The supplied import path is now importing. You can see the progress of that import below."
        redirect_to vm_import_path(:id => import.id)
      else
        flash[:error] = import.errors.full_messages.join(', ')
      end
    end
  end

  def upload
    if request.post?
      import = Import.new
      if import.upload(params[:import_archive_file])
        flash[:notice] = "The supplied import archive has been uploaded. You can now proceed to import the Virtual Machine it contains."
        redirect_to vm_imports_path
      else
        flash[:error] = import.errors.full_messages.join(', ')
      end
    end
  end

  def progress
    render :layout => false
  end

  def destroy
    if request.delete?
      @import.destroy
      flash[:notice] = "The selected import has now been deleted. The machine it imported still exists though, and needs to be deleted separately."
      redirect_to vm_imports_path
    end
  end

  private

  def find_import_from_id
    @import = Import.find(params[:id])
  end
end

app/helpers/import_helper.rb
module ImportHelper
end

app/views/import/_form.html.erb
<p>You must point the filepath to a valid OVF file, with it's corresponding MF and VMDK/VDI files in the same directory.</p>

<%= form_tag(vm_new_import_path, :method => :post) do %>

  <fieldset class="data_box">
    <div class="data">
      <div class="label">Filepath:</div>
      <div class="value"><%= text_field_tag('import[filepath]', (params[:import][:filepath] if params[:import]), :size => 60) %></div>
      <div class="break"></div>
    </div>
  </fieldset>

  <%= submit_tag 'Import Virtual Machine', :class => 'submit_button' %>

<% end %>

app/views/import/_progress.html.erb
<div class="status"><%= Import::STATUSES[@import.status.to_sym] %></div>
<div class="percent_imported">
  <div class="bar" style="width: <%= @import.percent_imported %>%;"></div>
  <div class="text"><%= @import.percent_imported %>%  </div>
</div>

<div class="reload"><%= link_to('Reload', '') unless @import.percent_imported > 0 || @import.completed? %></div>

<% if @import.completed? %>
  <div class="view_machine">
    <% if @import.machine %>
      <%= link_to('View Machine', vm_path(:uuid => @import.machine_uuid)) %>
    <% else %>
      (the imported machine has been<br />deleted since this import was run)
    <% end %>
  </div>
<% end %>

<%= javascript_tag("stop_progress_bar();") if @import.completed? %>
<%= javascript_tag("$('no_background_process').hide();") if @import.percent_imported > 0 %>

app/views/import/_upload_form.html.erb
<p>Please upload an archive (tar, gzip, or bzip) containing the OVF, MF, and VMDK/VDI files of the machine you want to import.</p>

<%= form_tag(vm_upload_import_path, :method => :post, :multipart => true) do %>

  <fieldset class="data_box">
    <div class="data">
      <%= file_field_tag('import_archive_file', :class => 'import_upload_field') %>
    </div>
  </fieldset>

  <%= submit_tag 'Upload Import Archive', :class => 'submit_button' %>

<% end %>

app/views/import/destroy.html.erb
<h2 class="heading">Are you sure you want to do this?</h2>

<p>You will only be deleting the record of the import.</p>

<p>The actual machine that was imported will need to be <strong>removed separately.</strong></p>

<p>Are you sure you want to do this?</p>

<%= form_tag(vm_import_destroy_path, :method => :delete) do %>
  <%= submit_tag "Yes, I'm sure." %>
<% end %>

app/views/import/index.html.erb
<h2 class="heading">Import a Virtual Machine</h2>

<h3>Available Imports</h3>
<% files = Dir[Rails.root.join('imports/**/*.ovf').to_s] %>
<% if files.size > 0 %>
  <ul>
  <% Dir[Rails.root.join('imports/*/*.ovf').to_s].each do |file| %>
    <li><%= link_to File.basename(file), vm_new_import_path(:import => { :filepath => file }) %></li>
  <% end %>
  </ul>
<% else %>
  <p>No imports available.</p>
<% end %>

<h3>Create Import from Filepath</h3>
<%= render 'form' %>

<h3>Upload Import Archive</h3>
<%= render 'upload_form' %>

<% previous_imports = Import.all %>
<% if previous_imports.size > 0 %>
  <h3>Previous Imports</h3>
  <table class="previous_imports_table">
    <tr class="import_headings">
      <th class="date">Imported</th>
      <th class="status">Status</th>
      <th class="filename">OVF Filename</th>
    </tr>
    <% previous_imports.each do |import| %>
      <tr class="import">
        <td class="date"><%= import.created_at.to_date %></td>
        <td class="status"><%= import.status %> <%= "(#{import.percent_imported}%)" if import.importing? %></td>
        <td class="filename"><%= File.basename(import.filepath) %></td>
        <td><%= link_to 'view import progress', vm_import_path(:id => import.id) if import.importing? %></td>
        <td>
          <% if import.completed? %>
            <% if import.machine %>
              <%= link_to '(view machine)', vm_path(:uuid => import.machine_uuid) %>
            <% else %>
              (deleted since imported)
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'delete', vm_import_destroy_path(:id => import.id) if import.failed? || import.completed? %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/import/new.html.erb
<h2 class="heading">Create Import from Filepath</h2>
<%= render 'form' %>

app/views/import/progress.html.erb
<%= render 'progress' %>

app/views/import/show.html.erb
<h2 class="heading">Importing <%= File.basename(@import.filepath) %>...</h2>

<div id="import_status"><%= render 'progress' %></div>

<%= javascript_tag("update_progress_bar('import_status', '#{vm_import_progress_path}');") unless @import.completed? %>

<% unless @import.completed? %>
  <div id="no_background_process">
    If the import remains at 0% for a minute or more,
    it's possible that the background server isn't
    running. Run <strong>script/delayed_job start</strong>
    to start it.
  </div>
<% end %>

<div id="return_to_imports"><%= link_to 'Return to Imports', vm_imports_path %></div>

app/views/import/upload.html.erb
<h2 class="heading">Upload Import Archive</h2>
<%= render 'upload_form' %>