config/routes.rb
VboxwebRb::Application.routes.draw do |map|
  match 'vm/imports'              => 'import#index',    :as => 'vm_imports'
  match 'vm/imports/new'          => 'import#new',      :as => 'vm_new_import'
  match 'vm/imports/upload'       => 'import#upload',   :as => 'vm_upload_import'
  match 'vm/imports/:id/progress' => 'import#progress', :as => 'vm_import_progress'
  match 'vm/imports/:id/destroy'  => 'import#destroy',  :as => 'vm_import_destroy'
  match 'vm/imports/:id'          => 'import#show',     :as => 'vm_import'
  
  match 'vm/:uuid/exports'              => 'export#index',    :as => 'vm_exports'
  match 'vm/:uuid/exports/new'          => 'export#new',      :as => 'vm_new_export'
  match 'vm/:uuid/exports/:id/progress' => 'export#progress', :as => 'vm_export_progress'
  match 'vm/:uuid/exports/:id/download' => 'export#download', :as => 'vm_export_download'
  match 'vm/:uuid/exports/:id/destroy'  => 'export#destroy',  :as => 'vm_export_destroy'
  match 'vm/:uuid/exports/:id'          => 'export#show',     :as => 'vm_export'

  match 'vm/:uuid/snapshots'             => 'snapshots#index',   :as => 'vm_snapshots'
  match 'vm/:uuid/snapshots/new'         => 'snapshots#new',     :as => 'vm_new_snapshot'
  match 'vm/:uuid/snapshots/:id/restore' => 'snapshots#restore', :as => 'vm_snapshot_restore'
  match 'vm/:uuid/snapshots/:id/destroy' => 'snapshots#destroy', :as => 'vm_snapshot_destroy'
  match 'vm/:uuid/snapshots/:id'         => 'snapshots#show',    :as => 'vm_snapshot'

  match 'vm/:uuid/settings' => 'vm#settings', :as => 'vm_settings'
  match 'vm/:uuid/destroy'  => 'vm#destroy',  :as => 'vm_destroy'
  match 'vm/:uuid/:command' => 'vm#control',  :as => 'vm_control'
  match 'vm/:uuid'          => 'vm#show',     :as => 'vm'

  match 'hd/:uuid/release' => 'hd#release', :as => 'hd_release'
  match 'hd/:uuid/remove'  => 'hd#remove',  :as => 'hd_remove'
  match 'hd/:uuid'         => 'hd#show',    :as => 'hd'

  root :to => 'homepage#index'
end

app/controllers/vm_controller.rb
class VmController < ApplicationController
  before_filter :find_virtual_machine_from_uuid
  before_filter :redirect_unless_vm_powered_off, :only => [:settings, :destroy]

  def show
  end

  def settings
    if request.put?
      begin
        vm_settings = convert_settings_in(params[:settings])

        %w{ audio_adapter bios hw_virt cpu vrdp_server }.each do |setting_type|
          settings = vm_settings.delete(setting_type.to_sym)
          next unless settings
          settings.each { |attribute, value| @vm.send(setting_type.to_sym).send("#{attribute}=", value) }
        end

        vm_settings.each { |attribute, value| @vm.send("#{attribute}=", value) }

        @vm.save
        flash[:notice] = "#{@vm.name} settings have been updated."
        redirect_to vm_path
      rescue VirtualBox::Exceptions::InvalidObjectStateException => e
        flash[:error] = "Cannot update settings because the virtual machine is either running, paused, or someone is already editing it."
        redirect_to vm_path
      end
    end
  end

  def destroy
    if request.delete?
      @vm.destroy
      flash[:notice] = "#{@vm.name} has been deleted."
      redirect_to root_path
    end
  end

  def control
    case params[:command]
    when 'start'
      @vm.start(:vrdp) if @vm.powered_off? || @vm.saved? || @vm.aborted?
      flash[:notice] = "#{@vm.name} has been started, but give it a minute to fully boot."
    when 'shutdown'
      @vm.shutdown if @vm.running?
      flash[:notice] = "#{@vm.name} is being shutdown. Please wait a bit for it to complete and refresh the page."
    when 'poweroff'
      @vm.stop if @vm.running? || @vm.paused?
      flash[:notice] = "#{@vm.name} has been powered off. Any unsaved data will have been lost."
    when 'pause'
      @vm.pause if @vm.running?
      flash[:notice] = "#{@vm.name} has been paused."
    when 'resume'
      @vm.resume if @vm.paused?
      flash[:notice] = "#{@vm.name} has been resumed."
    when 'save'
      @vm.save_state if @vm.running? || @vm.paused?
      flash[:notice] = "#{@vm.name} has been saved. You may resume at any time by pressing 'Start'."
    when 'discard'
      @vm.discard_state if @vm.saved?
      flash[:notice] = "#{@vm.name} saved state has been discarded."
    else
      flash[:error] = "Unsupported Virtual Machine Operation '#{params[:command]}'"
    end

    redirect_to vm_path
  end

  private

  def convert_settings_in(params)
    params.each do |attribute, value|
      next if attribute == 'ports' # ports needs to remain a string of numbers

      if value.is_a?(Hash)
        value = convert_settings_in(value)
      else
        case value
        when /^\d+$/ then value = value.to_i
        when 'true' then value = true
        when 'false' then value = false
        end
      end
      params[attribute] = value
    end

    params
  end
end

app/helpers/vm_helper.rb
module VmHelper

  # A list of specific OS types, grouped under their parent OS type
  # Contains the OS name, as well as the value virtualbox interprets
  def os_types
    @os_types ||= begin
      os_types_group = Hash.new
      VirtualBox::Global.global.lib.virtualbox.guest_os_types.each do |os_type|
        os_types_group[os_type.family_id] ||= Array.new
        os_types_group[os_type.family_id] << os_type
      end

      os_types_array = Array.new
      os_types_group.each do |family, operating_system_types|
        os_types_of_family = operating_system_types.collect { |os_type| [os_type.description, os_type.id] }
        os_types_array << [family, os_types_of_family]
      end

      os_types_array
    end
  end

  def options_for(option_type, current_value = nil)
    values = case option_type
    when :audio_controllers
      %w{ ac97 sb16 }
    when :audio_drivers
      if VirtualBox::Platform.mac?
        %w{ null core_audio }
      elsif VirtualBox::Platform.windows?
        %w{ null direct_sound winmm }
      elsif VirtualBox::Platform.linux?
        %w{ null alsa oss pulse }
      else
        %w{ null alsa core_audio direct_sound mmpm oss pulse sol_audio winmm }
      end
    when :auth_types
      %w{ null external guest }
    when :boot_types
      %w{ null floppy dvd hard_disk network }
    when :network_adapter_types
      %w{ null Am79C970A Am79C973 I82540EM I82543GC I82545EM Virtio }
    when :network_attachment_types
      %w{ null nat bridged internal host_only }
    end
    values = values.collect { |key| [t("vm.#{option_type}.#{key}"), key] }
    values = [[" - choose a #{option_type.to_s.humanize.singularize.downcase} - ", '']] + values
    options_for_select(values, current_value.to_s)
  end

  def get_system_property(property_name)
    @system_properties ||= VirtualBox::Global.global.system_properties
    @system_properties.send(property_name.to_sym)
  end

  def formatted_boot_order_from_vm(vm)
    boot_order = Array.new
    get_system_property(:max_boot_position).times do |i|
      boot_item = vm.interface.get_boot_order(i + 1).to_s
      boot_order << t("vm.boot_types.#{boot_item}") unless boot_item == 'null'
    end
    boot_order.join(', ')
  end

  def formatted_access_from_shared_folder(shared_folder)
    if shared_folder.accessible && shared_folder.writable
      "Full Access"
    elsif shared_folder.accessible
      "Read-only"
    end
  end

  def any_hard_drives_attached_to?(vm)
    vm.medium_attachments.any? { |ma| ma.type == :hard_disk }
  end

  def missing_hard_drive_attachment_warning
    content_tag(:div, "This Virtual Machine has no Hard Drives attached to it.
      Therefore, some functionality has been disabled.", :class => 'flash error')
  end

end

app/views/vm/_categories.html.erb
<div id="categories">
  <ul>
    <% buttons.each do |data_type| %>
      <li><%= link_to data_type.humanize, "##{data_type}", { :id => "#{data_type}_view_link", :'data-view' => data_type } %></li>
    <% end %>
  </ul>
  <div style="clear:both;"></div>
</div>

app/views/vm/_controls.html.erb
<div id="actions">
  <% if (@vm.powered_off? || @vm.saved? || @vm.aborted?) && any_hard_drives_attached_to?(@vm) %>
  <div class="action">
    <div class="icon"><%= link_to(vbicon('controls/vm/start_16px', 'Start'), "/vm/#{@vm.uuid}/start") %></div>
    <div class="label"><%= link_to('Start', "/vm/#{@vm.uuid}/start") %></div>
  </div>
  <% end %>

  <% if @vm.powered_off? %>
  <div class="action">
    <div class="icon"><%= link_to(vbicon('controls/vm/settings_16px', 'Settings'), vm_settings_path) %></div>
    <div class="label"><%= link_to('Settings', vm_settings_path) %></div>
  </div>

  <% if any_hard_drives_attached_to?(@vm) %>
  <div class="action">
    <div class="icon"><%= link_to(vbicon('controls/vm/export_16px', 'Exports'), vm_exports_path) %></div>
    <div class="label"><%= link_to('Exports', vm_exports_path) %></div>
  </div>

  <div class="action">
    <div class="icon"><%= link_to(vbicon('controls/vm/snapshots_16px', 'Snapshots'), vm_snapshots_path) %></div>
    <div class="label"><%= link_to('Snapshots', vm_snapshots_path) %></div>
  </div>
  <% end %>

  <div class="action">
    <div class="icon"><%= link_to(vbicon('controls/vm/delete_16px', 'Delete'), vm_destroy_path) %></div>
    <div class="label"><%= link_to('Delete', vm_destroy_path) %></div>
  </div>
  <% end %>

  <% if @vm.running? || @vm.starting? %>
  <div class="action">
    <div class="icon"><%= link_to(vbicon('controls/vm/shutdown_16px', 'Shutdown'), "/vm/#{@vm.uuid}/shutdown") %></div>
    <div class="label"><%= link_to('Shutdown', "/vm/#{@vm.uuid}/shutdown") %></div>
  </div>
  <% end %>

  <% if @vm.running? || @vm.paused? || @vm.starting? %>
  <div class="action">
    <div class="icon"><%= link_to(vbicon('controls/vm/poweroff_16px', 'Power off'), "/vm/#{@vm.uuid}/poweroff") %></div>
    <div class="label"><%= link_to('Power Off', "/vm/#{@vm.uuid}/poweroff") %></div>
  </div>

  <div class="action">
    <div class="icon"><%= link_to(vbicon('controls/vm/save_16px', 'Save'), "/vm/#{@vm.uuid}/save") %></div>
    <div class="label"><%= link_to('Save', "/vm/#{@vm.uuid}/save") %></div>
  </div>
  <% end %>

  <% if @vm.running? || @vm.starting? %>
  <div class="action">
    <div class="icon"><%= link_to(vbicon('controls/vm/pause_16px', 'Pause'), "/vm/#{@vm.uuid}/pause") %></div>
    <div class="label"><%= link_to('Pause', "/vm/#{@vm.uuid}/pause") %></div>
  </div>
  <% end %>

  <% if @vm.paused? %>
  <div class="action">
    <div class="icon"><%= link_to(vbicon('controls/vm/start_16px', 'Resume'), "/vm/#{@vm.uuid}/resume") %></div>
    <div class="label"><%= link_to('Resume', "/vm/#{@vm.uuid}/resume") %></div>
  </div>
  <% end %>

  <% if @vm.saved? %>
  <div class="action">
    <div class="icon"><%= link_to(vbicon('controls/vm/discard_16px', 'Discard'), "/vm/#{@vm.uuid}/discard") %></div>
    <div class="label"><%= link_to('Discard', "/vm/#{@vm.uuid}/discard") %></div>
  </div>
  <% end %>

  <div class="action refresh">
    <div class="icon"><%= link_to(vbicon('controls/vm/refresh_16px', 'Refresh'), "/vm/#{@vm.uuid}") %></div>
    <div class="label"><%= link_to('Refresh', "/vm/#{@vm.uuid}") %></div>
  </div>

  <div style="clear:both;"></div>
</div>

app/views/vm/destroy.html.erb
<h2 class="heading">Are you sure you want to do this?</h2>

<p>Deleting a Virtual Machine cannot be undone.</p>

<p>Once executed, the <strong>virtual machine will be gone for good</strong>.</p>

<p>Are you sure you want to do this?</p>

<%= form_tag(vm_destroy_path, :method => :delete) do %>
  <%= submit_tag "Yes, I'm sure." %>
<% end %>

app/views/vm/export.html.erb
<h3 class="heading">Exporting <%= @vm.name %></h3>

<p>
  Here you are able to export this Virtual Machine into
  a format other VirtualBox users are able to import
</p>

<%= form_tag(vm_export_path, :method => :post) do %>

  <fieldset class="data_box">
    <legend class="heading">Export Settings (required)</legend>
    <div class="data">
      <div class="label">Filename:</div>
      <div class="value"><%= text_field_tag('export[filename]') %>.ovf</div>
      <div class="break"></div>
    </div>
  </fieldset>

  <!-- <fieldset class="data_box">
    <legend class="heading">Additional Settings (optional)</legend>
    <div class="data">
      <div class="label">Product Name:</div>
      <div class="value"><%= text_field_tag('export[product]') %></div>
      <div class="break"></div>
    </div>
    <div class="data">
      <div class="label">Product URL:</div>
      <div class="value"><%= text_field_tag('export[producturl]') %></div>
      <div class="break"></div>
    </div>
    <div class="data">
      <div class="label">Vendor Name:</div>
      <div class="value"><%= text_field_tag('export[vendor]') %></div>
      <div class="break"></div>
    </div>
    <div class="data">
      <div class="label">Vendor URL:</div>
      <div class="value"><%= text_field_tag('export[vendorurl]') %></div>
      <div class="break"></div>
    </div>
    <div class="data">
      <div class="label">Version:</div>
      <div class="value"><%= text_field_tag('export[version]') %></div>
      <div class="break"></div>
    </div>
    <div class="data">
      <div class="label">EULA:</div>
      <div class="value"><%= text_area_tag('export[eula]', '', :rows => 15, :cols => 50) %></div>
      <div class="break"></div>
    </div>
  </fieldset> -->

  <%= submit_tag 'Export Virtual Machine' %> (may take several minutes)

<% end %>

app/views/vm/settings.html.erb
<h2 class="heading">Updating <%= @vm.name %></h2>

<div class="description_note">
  ( hover over any of the labels to get a description of what the value is for )
</div>

<%= render 'categories', :buttons => %w{ general system display audio } %>

<div id="vm_properties">
  <%= form_tag(vm_settings_path, :method => :put) do %>
    <% %w{ general system display audio }.each do |data_type| %>
      <%= render "vm/settings/#{data_type}" %>
    <% end %>
    <%= submit_tag 'Update Settings' %>
  <% end %>
</div>

app/views/vm/show.html.erb
<h2 class="heading">Viewing <%= @vm.name %></h2>

<%= missing_hard_drive_attachment_warning unless any_hard_drives_attached_to?(@vm) %>

<%= render 'controls' %>

<%= render 'categories', :buttons => %w{ general system display storage audio network usb shared_folders } %>

<div id="vm_properties">
  <% %w{ general system display storage audio network usb shared_folders }.each do |data_type| %>
    <%= render "vm/display/#{data_type}" %>
  <% end %>
</div>