config/routes.rb
VboxwebRb::Application.routes.draw do |map|
  match 'vm/imports'              => 'import#index',    :as => 'vm_imports'
  match 'vm/imports/new'          => 'import#new',      :as => 'vm_new_import'
  match 'vm/imports/upload'       => 'import#upload',   :as => 'vm_upload_import'
  match 'vm/imports/:id/progress' => 'import#progress', :as => 'vm_import_progress'
  match 'vm/imports/:id/destroy'  => 'import#destroy',  :as => 'vm_import_destroy'
  match 'vm/imports/:id'          => 'import#show',     :as => 'vm_import'
  
  match 'vm/:uuid/exports'              => 'export#index',    :as => 'vm_exports'
  match 'vm/:uuid/exports/new'          => 'export#new',      :as => 'vm_new_export'
  match 'vm/:uuid/exports/:id/progress' => 'export#progress', :as => 'vm_export_progress'
  match 'vm/:uuid/exports/:id/download' => 'export#download', :as => 'vm_export_download'
  match 'vm/:uuid/exports/:id/destroy'  => 'export#destroy',  :as => 'vm_export_destroy'
  match 'vm/:uuid/exports/:id'          => 'export#show',     :as => 'vm_export'

  match 'vm/:uuid/snapshots'             => 'snapshots#index',   :as => 'vm_snapshots'
  match 'vm/:uuid/snapshots/new'         => 'snapshots#new',     :as => 'vm_new_snapshot'
  match 'vm/:uuid/snapshots/:id/restore' => 'snapshots#restore', :as => 'vm_snapshot_restore'
  match 'vm/:uuid/snapshots/:id/destroy' => 'snapshots#destroy', :as => 'vm_snapshot_destroy'
  match 'vm/:uuid/snapshots/:id'         => 'snapshots#show',    :as => 'vm_snapshot'

  match 'vm/:uuid/settings' => 'vm#settings', :as => 'vm_settings'
  match 'vm/:uuid/destroy'  => 'vm#destroy',  :as => 'vm_destroy'
  match 'vm/:uuid/:command' => 'vm#control',  :as => 'vm_control'
  match 'vm/:uuid'          => 'vm#show',     :as => 'vm'

  match 'hd/:uuid/release' => 'hd#release', :as => 'hd_release'
  match 'hd/:uuid/remove'  => 'hd#remove',  :as => 'hd_remove'
  match 'hd/:uuid'         => 'hd#show',    :as => 'hd'

  root :to => 'homepage#index'
end

app/models/export.rb
class Export < ActiveRecord::Base

  validates_presence_of :machine_uuid, :export_data

  serialize :export_data

  before_create :set_status_and_percent_exported_if_blank

  STATUSES = {
    :starting => 'Starting...',
    :failed => 'Failed... (is the vm running?)',
    :exporting => 'Exporting...',
    :packaging => 'Packaging...',
    :completed => "Completed"
  }

  Export::STATUSES.keys.each do |status_value|
    define_method "#{status_value}?" do
      status.to_s.downcase == status_value.to_s
    end
  end

  def machine
    @machine ||= VirtualBox::VM.find(machine_uuid)
  end

  def filename
    @filename ||= export_data[:filename].to_s.parameterize
  end

  def filepath
    @filepath ||= Rails.root.join('exports', filename, filename+".ovf").to_s
  end

  def valid_export_data_keys
    %w{ description product product_url vendor vendor_url version license }
  end

  def export_options
    options = Hash.new
    export_data.each do |key, value|
      next unless valid_export_data_keys.include?(key.to_s) && value.present?
      options[key.to_sym] = value
    end
    options
  end

  def export!
    unless machine.powered_off?
      update_attribute(:status, 'failed')
      return false
    end
    update_attribute(:status, 'exporting')
    machine.export(filepath, export_options) do |progress|
      update_attribute(:percent_exported, progress.percent)
    end
    update_attribute(:status, 'packaging')
    package
    update_attribute(:status, 'completed')
  rescue
    update_attribute(:status, 'failed')
  end
  handle_asynchronously :export!

  def packaged_dir_path
    Rails.root.join('exports', filename).to_s
  end

  def packaged_file_path
    Rails.root.join('exports', filename, filename+".tar").to_s
  end

  def package
    unless File.exist?(packaged_file_path)
      require 'zlib'
      require 'archive/tar/minitar'
      Dir.chdir(packaged_dir_path) do
        exportable_files = Dir.glob('*')
        File.open(packaged_file_path, 'wb') do |tar|
          ::Archive::Tar::Minitar::Output.open(tar) do |output|
            exportable_files.each { |f| ::Archive::Tar::Minitar.pack_file(f, output) }
          end
        end
      end
    end

    packaged_file_path
  end

  private

  def set_status_and_percent_exported_if_blank
    self.status = 'starting' if self.status.blank?
    self.percent_exported = 0 if self.percent_exported.blank?
  end

  def validate
    if filename.blank?
      errors[:base] << "You must specify a filename to export to."
      false
    elsif File.directory?(packaged_dir_path)
      errors[:base] << "Export of this name already exists. Please choose another."
      false
    else
      true
    end
  end

end

app/controllers/export_controller.rb
class ExportController < ApplicationController
  before_filter :find_virtual_machine_from_uuid, :only => [:index, :new]
  before_filter :find_export_from_id, :except => [:index, :new]
  before_filter :redirect_unless_vm_powered_off, :only => [:new]

  def index
  end

  def show
  end

  def new
    if request.post?
      export = Export.new(:machine_uuid => @vm.uuid, :export_data => params[:export])
      if export.save
        export.export!
        flash[:notice] = "#{@vm.name} is now exporting. You can see the progress of that export below."
        redirect_to vm_export_path(:id => export.id)
      else
        flash[:error] = export.errors.full_messages.join(', ')
      end
    end
  end

  def progress
    render :layout => false
  end

  def download
    send_file(@export.package, :type => 'application/x-tar')
  end

  def destroy
    if request.delete?
      require 'fileutils'
      FileUtils.rm_rf(@export.packaged_dir_path) if File.directory?(@export.packaged_dir_path)
      @export.destroy
      flash[:notice] = "The selected export has now been deleted."
      redirect_to vm_exports_path
    end
  end

  private

  def find_export_from_id
    @export = Export.find(params[:id])
  end
end

app/helpers/export_helper.rb
module ExportHelper
end

app/views/export/_form.html.erb
<p>
  Here you are able to export this Virtual Machine into
  a format other VirtualBox users are able to import.
</p>

<%= form_tag(vm_new_export_path, :method => :post) do %>

  <fieldset class="data_box">
    <legend class="heading">Export Settings (required)</legend>
    <div class="data">
      <div class="label">Filename:</div>
      <div class="value"><%= text_field_tag('export[filename]', '', :size => 55) %>.ovf</div>
      <div class="break"></div>
    </div>
  </fieldset>

  <fieldset class="data_box">
    <legend class="heading">Additional Settings (optional)</legend>
    <div class="data">
      <div class="label">Description:</div>
      <div class="value"><%= text_area_tag('export[description]', '', :rows => 6, :cols => 40)  %></div>
      <div class="break"></div>
    </div>
    <div class="data">
      <div class="label">Product Name:</div>
      <div class="value"><%= text_field_tag('export[product]', '', :size => 55) %></div>
      <div class="break"></div>
    </div>
    <div class="data">
      <div class="label">Product URL:</div>
      <div class="value"><%= text_field_tag('export[product_url]', '', :size => 55) %></div>
      <div class="break"></div>
    </div>
    <div class="data">
      <div class="label">Vendor Name:</div>
      <div class="value"><%= text_field_tag('export[vendor]', '', :size => 55) %></div>
      <div class="break"></div>
    </div>
    <div class="data">
      <div class="label">Vendor URL:</div>
      <div class="value"><%= text_field_tag('export[vendor_url]', '', :size => 55) %></div>
      <div class="break"></div>
    </div>
    <div class="data">
      <div class="label">Version:</div>
      <div class="value"><%= text_field_tag('export[version]', '', :size => 55) %></div>
      <div class="break"></div>
    </div>
    <div class="data">
      <div class="label">EULA:</div>
      <div class="value"><%= text_area_tag('export[license]', '', :rows => 6, :cols => 40) %></div>
      <div class="break"></div>
    </div>
  </fieldset>

  <%= submit_tag 'Export Virtual Machine' %>

<% end %>

app/views/export/_progress.html.erb
<div class="status"><%= Export::STATUSES[@export.status.to_sym] %></div>
<div class="percent_exported">
  <div class="bar" style="width: <%= @export.percent_exported %>%;"></div>
  <div class="text"><%= @export.percent_exported %>%  </div>
</div>

<div class="reload"><%= link_to('Reload', '') unless @export.percent_exported > 0 || @export.completed? %></div>

<% if @export.completed? %>
  <div class="download">
    <% if File.exist?(@export.packaged_file_path) || File.exist?(@export.filepath) %>
      <%= link_to('Download', vm_export_download_path) %>
    <% else %>
      (the files needed to download have<br />been deleted since this export was run)
    <% end %>
  </div>
<% end %>

<%= javascript_tag("stop_progress_bar();") if @export.completed? %>
<%= javascript_tag("$('no_background_process').hide();") if @export.percent_exported > 0 %>

app/views/export/destroy.html.erb
<h2 class="heading">Are you sure you want to do this?</h2>

<p>Deleting a Virtual Machine export cannot be undone.</p>

<p>Once executed, the <strong>virtual machine export will be gone for good</strong>.</p>

<p>Are you sure you want to do this?</p>

<%= form_tag(vm_export_destroy_path, :method => :delete) do %>
  <%= submit_tag "Yes, I'm sure." %>
<% end %>

app/views/export/index.html.erb
<h2 class="heading"><%= @vm.name %> Exports</h2>

<h3>Create Export</h3>
<%= render 'form' %>

<% previous_exports = Export.find_all_by_machine_uuid(@vm.uuid) %>
<% if previous_exports.size > 0 %>
  <h3>Previous Exports</h3>
  <table class="previous_exports_table">
    <tr class="export_headings">
      <th class="date">Exported</th>
      <th class="filename">Filename</th>
      <th class="status">Status</th>
    </tr>
    <% previous_exports.each do |export| %>
      <tr class="export">
        <td class="date"><%= export.created_at.to_date %></td>
        <td class="filename"><%= export.filename %></td>
        <td class="status"><%= export.status %> <%= "(#{export.percent_exported}%)" if export.exporting? %></td>
        <td><%= link_to 'view export progress', vm_export_path(:id => export.id) if export.exporting? %></td>
        <td>
          <% if export.completed? %>
            <% if File.exist?(export.packaged_file_path) || File.exist?(export.filepath) %>
              <%= link_to 'download', vm_export_download_path(:id => export.id) %>
            <% else %>
              (deleted since exported)
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'delete', vm_export_destroy_path(:id => export.id) if export.failed? || export.completed? %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/export/new.html.erb
<h2 class="heading">Export <%= @vm.name %></h2>
<%= render 'form' %>

app/views/export/show.html.erb
<h2 class="heading">Exporting <%= @export.machine.name %>...</h2>

<div id="export_status"><%= render 'progress' %></div>

<%= javascript_tag("update_progress_bar('export_status', '#{vm_export_progress_path}');") unless @export.completed? %>

<% unless @export.completed? %>
  <div id="no_background_process">
    If the export remains at 0% for a minute or more,
    it's possible that the background server isn't
    running. Run <strong>script/delayed_job start</strong>
    to start it.
  </div>
<% end %>

<div id="return_to_exports"><%= link_to 'Return to Exports', vm_exports_path %></div>