config/routes.rb
VboxwebRb::Application.routes.draw do |map|
  match 'vm/imports'              => 'import#index',    :as => 'vm_imports'
  match 'vm/imports/new'          => 'import#new',      :as => 'vm_new_import'
  match 'vm/imports/upload'       => 'import#upload',   :as => 'vm_upload_import'
  match 'vm/imports/:id/progress' => 'import#progress', :as => 'vm_import_progress'
  match 'vm/imports/:id/destroy'  => 'import#destroy',  :as => 'vm_import_destroy'
  match 'vm/imports/:id'          => 'import#show',     :as => 'vm_import'
  
  match 'vm/:uuid/exports'              => 'export#index',    :as => 'vm_exports'
  match 'vm/:uuid/exports/new'          => 'export#new',      :as => 'vm_new_export'
  match 'vm/:uuid/exports/:id/progress' => 'export#progress', :as => 'vm_export_progress'
  match 'vm/:uuid/exports/:id/download' => 'export#download', :as => 'vm_export_download'
  match 'vm/:uuid/exports/:id/destroy'  => 'export#destroy',  :as => 'vm_export_destroy'
  match 'vm/:uuid/exports/:id'          => 'export#show',     :as => 'vm_export'

  match 'vm/:uuid/snapshots'             => 'snapshots#index',   :as => 'vm_snapshots'
  match 'vm/:uuid/snapshots/new'         => 'snapshots#new',     :as => 'vm_new_snapshot'
  match 'vm/:uuid/snapshots/:id/restore' => 'snapshots#restore', :as => 'vm_snapshot_restore'
  match 'vm/:uuid/snapshots/:id/destroy' => 'snapshots#destroy', :as => 'vm_snapshot_destroy'
  match 'vm/:uuid/snapshots/:id'         => 'snapshots#show',    :as => 'vm_snapshot'

  match 'vm/:uuid/settings' => 'vm#settings', :as => 'vm_settings'
  match 'vm/:uuid/destroy'  => 'vm#destroy',  :as => 'vm_destroy'
  match 'vm/:uuid/:command' => 'vm#control',  :as => 'vm_control'
  match 'vm/:uuid'          => 'vm#show',     :as => 'vm'

  match 'hd/:uuid/release' => 'hd#release', :as => 'hd_release'
  match 'hd/:uuid/remove'  => 'hd#remove',  :as => 'hd_remove'
  match 'hd/:uuid'         => 'hd#show',    :as => 'hd'

  root :to => 'homepage#index'
end

app/controllers/snapshots_controller.rb
class SnapshotsController < ApplicationController
  before_filter :find_virtual_machine_from_uuid
  before_filter :find_snapshot_from_id, :except => [:index, :new]

  def index
  end

  def show
    # Once we have the snapshot, lets overwrite it with the machine from
    # the snapshot (as each snapshot has its own machine and settings)
    @vm = @snapshot.machine
  end

  def new
    if request.post?
      if params[:snapshot] && params[:snapshot][:name].present?
        @vm.take_snapshot(params[:snapshot][:name], params[:snapshot][:description])
        redirect_to vm_snapshots_path
      else
        flash[:error] = "Please specify a snapshot name."
      end
    end
  end

  def restore
    if request.put?
      @snapshot.restore
      flash[:notice] = "The selected snapshot has been restored."
      redirect_to vm_snapshots_path
    end
  end

  def destroy
    if request.delete?
      @snapshot.destroy
      flash[:notice] = "The selected snapshot has been destroyed."
      redirect_to vm_snapshots_path
    end
  end

  private

  def find_snapshot_from_id
    @snapshot = @vm.find_snapshot(params[:id])
  end
end

app/helpers/snapshots_helper.rb
module SnapshotsHelper
  def snapshot_tree_from(root_snapshot, current_snapshot)
    html = "<ul id='snapshots_tree'>"
    html += "<li class='#{"current_parent" if root_snapshot.uuid == current_snapshot.uuid}'>"
    html += link_to(root_snapshot.name, vm_snapshot_path(:id => root_snapshot.uuid))
    html += " (#{time_ago_in_words(root_snapshot.time_stamp, true)} ago)"
    html += children_snapshot_tree_from(root_snapshot, current_snapshot)
    html += "</li>"
    html += "</ul>"
    html
  end

  def children_snapshot_tree_from(parent_snapshot, current_snapshot)
    return String.new unless parent_snapshot.children.size > 0 || parent_snapshot.uuid == current_snapshot.uuid

    html = "<ul>"
    parent_snapshot.children.each do |child_snapshot|
      html += "<li class='#{"current_parent" if child_snapshot.uuid == current_snapshot.uuid}'>"
      html += link_to(child_snapshot.name, vm_snapshot_path(:id => child_snapshot.uuid))
      html += " (#{time_ago_in_words(child_snapshot.time_stamp, true)} ago)"
      html += children_snapshot_tree_from(child_snapshot, current_snapshot)
      html += "</li>"
    end
    html += "<li class='current_state'>Current State</li>" if parent_snapshot.uuid == current_snapshot.uuid
    html += "</ul>"
  end
end

app/views/snapshots/destroy.html.erb
<h2 class="heading">Are you sure you want to do this?</h2>

<p>Deleting a snapshot will cause the state information saved in it to be lost, and
  disk data spread over several image files that VirtualBox has created together with
  the snapshot will be merged into one file. This can be a lengthy process, and the
  information in the snapshot cannot be recovered.</p>

<p>Are you sure you want to do this?</p>

<%= form_tag(vm_snapshot_destroy_path, :method => :delete) do %>
  <%= submit_tag "Yes, I'm sure." %>
<% end %>

app/views/snapshots/index.html.erb
<h2 class="heading">Viewing Snapshots for <%= @vm.name %></h2>

<div id="actions">
  <div class="action">
    <div class="icon"><%= link_to(vbicon('controls/vm/take_snapshot_16px', 'Take Snapshot'), vm_new_snapshot_path) %></div>
    <div class="label"><%= link_to('Take Snapshot', vm_new_snapshot_path) %></div>
  </div>

  <div class="action refresh">
    <div class="icon"><%= link_to(vbicon('controls/vm/refresh_16px', 'Refresh'), "") %></div>
    <div class="label"><%= link_to('Refresh', "") %></div>
  </div>

  <div style="clear:both;"></div>
</div>

<h3>What are snapshots?</h3>
<p>
  Snapshots are a simple and effective way of capturing an operating system at the time it
  is taken. Perhaps you need to install something on the operating system, and you're not
  sure if it'll go smoothly. Creating a snapshot will ensure that if something goes wrong,
  you can easily revert to a snapshot you've taken.
</p>

<h3>Current Snapshot Tree</h3>
<% if @vm.root_snapshot %>
  <%=raw snapshot_tree_from(@vm.root_snapshot, @vm.current_snapshot) %>
<% else %>
  <p>No snapshots available.</p>
<% end %>

app/views/snapshots/new.html.erb
<h2 class="heading">Take Snapshot of <%= @vm.name %></h2>

<%= form_tag(vm_new_snapshot_path, :method => :post) do %>

  <fieldset class="data_box">
    <legend class="heading">Snapshot Settings</legend>
    <div class="data">
      <div class="label">Snapshot Name:</div>
      <div class="value"><%= text_field_tag('snapshot[name]') %></div>
      <div class="break"></div>
    </div>
    <div class="data">
      <div class="label">Snapshot Description:</div>
      <div class="value"><%= text_area_tag('snapshot[description]', nil, :rows => 4, :cols => 18) %></div>
      <div class="break"></div>
    </div>
  </fieldset>

  <%= submit_tag 'Create Snapshot' %>

<% end %>

app/views/snapshots/restore.html.erb
<h2 class="heading">Are you sure you want to do this?</h2>

<p>Restoring a snapshot will cause you to lose you current machine state, which cannot be recovered.</p>

<p>Are you sure you want to do this?</p>

<%= form_tag(vm_snapshot_restore_path, :method => :put) do %>
  <%= submit_tag "Yes, I'm sure." %>
<% end %>

app/views/snapshots/show.html.erb
<h2 class="heading">Viewing Snapshot: <%= @snapshot.name %></h2>

<div id="actions">
  <div class="action">
    <div class="icon"><%= link_to(vbicon('controls/vm/restore_snapshot_16px', 'Restore Snapshot'), vm_snapshot_restore_path) %></div>
    <div class="label"><%= link_to('Restore Snapshot', vm_snapshot_restore_path) %></div>
  </div>

  <div class="action">
    <div class="icon"><%= link_to(vbicon('controls/vm/delete_snapshot_16px', 'Delete Snapshot'), vm_snapshot_destroy_path) %></div>
    <div class="label"><%= link_to('Delete Snapshot', vm_snapshot_destroy_path) %></div>
  </div>

  <div class="action refresh">
    <div class="icon"><%= link_to(vbicon('controls/vm/refresh_16px', 'Refresh'), "") %></div>
    <div class="label"><%= link_to('Refresh', "") %></div>
  </div>

  <div style="clear:both;"></div>
</div>

<%= render 'vm/categories', :buttons => %w{ general system display storage audio network usb shared_folders } %>

<div id="vm_properties">
  <% %w{ general system display storage audio network usb shared_folders }.each do |data_type| %>
    <%= render "vm/display/#{data_type}" %>
  <% end %>
</div>